workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Generate iOS project
        script: |
          flutter create .

      - name: Build iOS (no signing)
        script: |
          flutter build ipa --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
